api/urls.py
from django.conf.urls import url

from .views import PostListView, CommentListView, PostCreateView, CommentCreateView, PostDeleteView, CommentDeleteView

urlpatterns = [

    # все посты
    url(r'posts/', PostListView.as_view(), name='rest_posts_list'),

    # комментарии к посту
    url(r'comments/(?P<pk>\d+)/', CommentListView.as_view(), name='rest_comments_list'),

    # добавление нового поста
    url(r'post/add/', PostCreateView.as_view(), name='rest_post_add'),

    # добавление нового комментария
    url(r'comment/add/', CommentCreateView.as_view(), name='rest_comment_add'),

    # удаление поста по номеру
    url(r'post/delete/(?P<pk>\d+)/', PostDeleteView.as_view(), name='rest_post_delete'),

    # удаление комментария по номеру
    url(r'comment/delete/(?P<pk>\d+)/', CommentDeleteView.as_view(), name='rest_comment_delete'),

]

blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve

from blog import settings

# import blog_app.urls


urlpatterns = [

    url(r'^admin/', admin.site.urls),

    url(r'^blog/', include('blog_app.urls')),  # blog_app

    url('^registration/', include('django.contrib.auth.urls')),

    url('^registration/', include('registration.urls')),

    url('^api/', include('api.urls')),  # rest_ framework

    ]


if settings.DEBUG:
    urlpatterns.append(url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}))

blog_app/urls.py
from django.conf.urls import url

from .views import PostsList, PostDetail, CommentsList, CommentCreate, CommentDelete, CreateSubscribe, DeleteSubscribe

urlpatterns = [

    url(r'posts/', PostsList.as_view(), name='post_list'),

    url(r'detail/(?P<pk>\d+)/', PostDetail.as_view(), name='post_detail'),

    url(r'comments/(?P<pk>\d+)/', CommentsList.as_view(), name='comments_list'),

    url(r'comment/add/', CommentCreate.as_view(), name='comment_create'),

    url(r'subscribe/add', CreateSubscribe.as_view(), name='subscribe_create'),

    url(r'subscribe/delete/(?P<pk>\d+)/', DeleteSubscribe.as_view(), name='subscribe_delete'),

    url(r'comment/delete/(?P<pk>\d+)/', CommentDelete.as_view(), name='comment_delete'),

    # url(r'registration/login/', auth_views.login, name='login'),
]

blog_app/models.py
from django.contrib.auth.models import User
from django.db import models


class Post(models.Model):
    """Запись в блоге"""

    post_title = models.CharField(max_length=30, unique=True, )

    post_text = models.TextField(max_length=500)

    post_date = models.DateField(auto_now=True)

    post_image = models.ImageField(blank=True, upload_to='blog_app/post_images', default='')

    # def __str__(self):

    #  return 'id: '+str(self.id)+' text: '+self.post_title


class Comment(models.Model):
    """Комментарий к посту"""

    comment_post = models.ForeignKey(Post, related_name='comments')

    comment_text = models.TextField(max_length=500, )

    comment_date = models.DateField(auto_now_add=True)

    comment_author = models.ForeignKey(User, related_name='comments', default='')

    def __str__(self):
        return self.comment_text[:50]


class Subscribe(models.Model):
    """Подписка на новые сообщения"""

    subscribe_user = models.OneToOneField(User, default='')

    email = models.EmailField(unique=True)

    def __str__(self):
        # return User.objects.get(id=self.subscribe_user)

        return str(self.id) + "_" + self.email + "_" + str(self.subscribe_user.id)

blog_app/forms.py
from django.forms import ModelForm
from django.forms.widgets import HiddenInput

from .models import Comment, Subscribe


class CommentCreateForm(ModelForm):
    """форма создания комментария к посту, используется в class CommentsList в файле blog_app/views.py"""

    class Meta:
        model = Comment

        fields = '__all__'

        widgets = {'comment_post': HiddenInput(), 'comment_author': HiddenInput()}

        labels = {'comment_text': ''}


class CreateSubscribeForm(ModelForm):
    """ форма создания подписки на новые комментарии"""

    class Meta:
        model = Subscribe

        fields = '__all__'

        widgets = {'subscribe_user': HiddenInput()}

        labels = {'email': 'Ваш адрес'}

blog_app/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views import View
from django.views.generic.detail import DetailView
from django.views.generic.edit import DeleteView, CreateView
from django.views.generic.list import ListView

from .forms import CommentCreateForm, CreateSubscribeForm
from .models import Post, Comment, Subscribe
from .tasks import comment_add_log, send_mail_to_subscribers


class PostsList(ListView):
    """Вывод всех постов"""

    model = Post

    context_object_name = 'posts'

    def get_context_data(self, **kwargs):
        """Добавляет в контекст id подписки, для вывода в шаблоне ссылки на страницу подписки"""

        context = super(PostsList, self).get_context_data(**kwargs)

        if Subscribe.objects.filter(subscribe_user=self.request.user.id).exists():
            context['subscribe_id'] = (Subscribe.objects.get(subscribe_user=self.request.user.id)).id

        return context


class PostDetail(LoginRequiredMixin, DetailView):
    """Вывод полного текста поста с последними  пятью комментариями"""

    login_url = reverse_lazy('login')

    model = Post

    context_object_name = 'post'

    def get_object(self, queryset=None):
        return get_object_or_404(Post, id=self.kwargs.get('pk'))

    def get_context_data(self, **kwargs):
        """Добавляет к контексту при выводе поста часть комментариев"""

        comments = Comment.objects.all().order_by('comment_date')[0:5]

        context = super(PostDetail, self).get_context_data(**kwargs)

        context['comments'] = comments

        return context


class CommentsList(ListView):
    """Вывод всех комментариев к посту"""

    model = Comment

    context_object_name = 'comments'

    def get_queryset(self):
        if Post.objects.filter(id=self.kwargs.get('pk')).exists():

            return Comment.objects.filter(comment_post_id=self.kwargs.get('pk'))

        else:

            raise Http404

    def get_context_data(self, **kwargs):
        """Добавляет в контекст форму для добавления нового комментария"""

        pk = self.kwargs.get('pk')

        context = super(CommentsList, self).get_context_data(**kwargs)

        context['form'] = CommentCreateForm(initial={'comment_post': pk, 'comment_author': self.request.user})

        return context


class CommentCreate(View):
    """Добавление комментария к посту"""

    def post(self, request):
        form = CommentCreateForm(request.POST)

        if form.is_valid():
            pk = form.cleaned_data.get('comment_post').id  # номер поста, по которому выбираются комментарии

            form.save()

            # блок задач celery

            comment_add_log.delay(str(request.user))

            send_mail_to_subscribers.delay(form.cleaned_data['comment_text'])

            # конец блока задач celery

            return redirect(reverse('comments_list', args=[pk]))

        raise Http404


class CommentDelete(DeleteView):
    """Удаление комментария"""

    model = Comment

    def get_success_url(self):
        """Возвращает url с текущим постом"""

        comment = Comment.objects.get(id=self.kwargs.get('pk'))

        return reverse_lazy('comments_list', args=[comment.comment_post.id])

    def get(self, request, *args, **kwargs):
        return self.post(self, request, *args, *kwargs)


# TODO
class CreateSubscribe(CreateView):
    """Создание подписки"""

    template_name = 'blog_app/subscribe_create_form.html'

    form_class = CreateSubscribeForm

    # success_url = reverse_lazy('subscribe_create')

    def get_initial(self):

        return {'subscribe_user': self.request.user.id}

    def get_success_url(self):

        return reverse_lazy('post_list')

        # def get_context_data(self, **kwargs):

    #        if not Subscribe.objects.filter(subscribe_user=self.request.user.id).exists():
    #
    #           context = super(CreateView,self).get_context_data(**kwargs)
    #
    #           return context

    #        else:

    #           pass

    def get(self, request):

        if Subscribe.objects.filter(subscribe_user=self.request.user.id).exists():

            return HttpResponse('<p><h3>Вы уже подписаны</h3>')  # redirect('post_list')

        else:

            return super(CreateView, self).get(request)


class DeleteSubscribe(DeleteView):
    """Удаление подписки"""

    model = Subscribe

    success_url = reverse_lazy('post_list')

    def get(self, request, *args, **kwargs):
        return self.post(self, request, *args, *kwargs)

blog_app/templates/blog_app/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title%}{% endblock title%}</title>
</head>
<body>


<div class="container-fluid">

    <div class="row">

    </div>

    <div class="row blog-nav">

        {% if user.is_authenticated %}

             <div class="col-md-4 col-md-offset-1 ">

                <p class="text-left"> Ну здравствуй мой дорогой друг, {{user}}</p>

             </div>

             <div class="col-md-4">

                 <p class="text-left "> Если не можешь это читать, то можешь  <a href="{% url 'logout' %}">  выйти </a> </p>

             </div>


             <div class="col-md-3">


                 {% if not subscribe_id %}

                     <p class="text-left"> или <a href="{% url 'subscribe_create' %}"> подписаться </a> </p>

                 {% else %}


                      <p class="text-left"> или <a href="{% url 'subscribe_delete' subscribe_id %}"> отписаться </a> </p>

                 {% endif %}

             </div>


        {% else %}

             <div class="col-md-2 col-md-offset-1">

                 <p class="text-left"> <a href="{% url 'registration_view' %}"> Зарегистрироваться </a> </p>

             </div>

             <div class="col-md-2 ">

                 <p class="text-left"> <a href="{% url 'login'%}?next= {{request.path}}"> Войти </a> </p>

             </div>

        {% endif %}

        </div>

    </div>
</div>


   <p></p>
   <p></p>


 <link rel="stylesheet" type="text/css" href="{% static 'blog_app/css/blog.css'%}"/>

 <link rel="stylesheet" type="text/css" href="{% static 'blog_app/css/bootstrap.min.css'%}"/>

 <link rel="stylesheet" type="text/css" href="{% static 'blog_app/css/bootstrap-theme.min.css'%}"/>

 <link rel="stylesheet" type="text/css" href="{% static 'blog_app/css/bootstrap-theme.min.css'%}" />



 <div class="row">

     <div class="col-md-8 col-md-offset-1">

            {% block content%}

            {% endblock content%}


     </div>

     <div class="col-md-3 col-md-offset-0 right-sidebar">


     </div>

 </div>

</body>
</html>

blog_app/templates/blog_app/comment_create_form.html
{% extends "blog_app/base.html" %}

{% block title%}


{% endblock title%}

{% if user.is_authenticated %}
 {% block content %}



    <form action="{% url 'comment_create' %} " method="POST" >

        {% csrf_token%}

        {{ form.as_p }}

    <input type="submit" value="OK">

    </form>

{% else%}








 {% endblock content %}

{% endif %}

blog_app/templates/blog_app/comment_list.html
{% extends "blog_app/base.html" %}

 {% block content %}

<ul>

<p>  {{post.id}} </p>

     <!-- <p>  {{post.post_title}} </p>

   <p>  {{post.post_text}} </p> -->


    {% for comment in comments %}


       <li>

           <p>{{comment.comment_text }}</p>

           {% if comment.comment_author == request.user %}

           <p> <a href="{% url 'comment_delete' comment.id %}"> Удалить свой комментарий  </a> </p>


           {% endif%}

       </li>


     {% empty %}

    <p> Будь первым, мужик! </p>

    {% endfor %}

  <form action=" {% url 'comment_create' %}" method="POST" >

        {% csrf_token%}

        <label for="id_comment_text">Пиши сюда:</label>

        {{ form.as_p }}

    <input type="submit" value="OK">

    </form>



</ul>

 {% endblock content %}

blog_app/templates/blog_app/post_detail.html
{% extends "blog_app/base.html" %}

              {% block title%}

                        {{post.post_title}}

                {% endblock title%}

                 {% block content %}

<div class="container-fluid">



               <h2 class="blog-post-title">{{post.post_title}}</h2>

                        <p class="blog-post-detail-text">{{post.post_text }}</p>



                 <u>  <h4>Отзывы и предложения:</h4></u>

                {% for comment in comments %}


                    <p>{{comment.comment_text}}</p>

                    <p>Автор: {{comment.comment_author}} Дата публикации: {{comment.comment_date}}</p>

                   <p></p>


                {% empty%}

                <p> Нет ни одного-одинешенького отзыва или предложения :(</p>

                   <p><a href="{% url 'comments_list' post.id   %}"> Но ты можешь его сделать!!! </a></p>


                {% endfor%}

                 {% if comments%}

                        <p><a href="{% url 'comments_list' post.id   %}"> Читать все отзывы и предложения </a></p>

                {% endif %}




</div>

{% endblock content %}

blog_app/templates/blog_app/post_list.html
{% extends "blog_app/base.html" %}

 {% block content %}



<div class="container-fluid">



<!--<ul> -->

    {% for post in posts %}



            <!--    <li>-->

                    <h2 class="blog-post-title">{{post.post_title}}</h2>



                    <p class="blog-post-list-text">{{post.post_text|truncatewords:40}}</p>



                    {% if post.post_image%}

                         <p> <img src="{{ post.post_image.url}} ">  </p>

                    {%endif%}



                        <p><a href="{% url 'post_detail' post.id  %}"> Подробнее.. </a> </p>
               <!--   </li>-->


    {% endfor %}

<!-- </ul>-->

</div>

 {% endblock content %}

blog_app/templates/blog_app/subscribe_create_form.html
{% extends "blog_app/base.html" %}

{% block title%}


{% endblock title%}


 {% block content %}





    <form action="{% url 'subscribe_create' %} " method="POST" >

        {% csrf_token %}


        {{ form.as_p }}




    <input type="submit" value="Подписаться">



    </form>







 {% endblock content %}